version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-bootstrap
    versions:
    - 1.4.0
    - 1.4.3
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: clipboard-polyfill
    versions:
    - 3.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
